services:
  napcat:
    container_name: napcat
    image: mlikiowa/napcat-docker:v4.4.4

  twitter-subscriber:
    build:
      context: .
    restart: always
    working_dir: /arona/apps/subscribe
    environment:
      # TODO
      HOSTNAME: twitter-subscriber
      ONEBOT_ORIGIN: napcat
    command: npm run start

  backup:
    build:
      context: .
    restart: always
    working_dir: /arona/apps/backup
    environment:
      # TODO
      ONEBOT_ORIGIN: napcat
    command: npm run start:db
