services:
  # arona:
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/arona.Dockerfile
  #   restart: always
  #   volumes:
  #     - type: bind
  #       source: /var/lib/arona
  #       target: /lib

  db-worker:
    build:
      context: .
      dockerfile: ./dockerfiles/db.Dockerfile
    restart: always
    volumes:
      - type: bind
        source: /var/lib/arona
        target: /store
