import Head from "next/head";
import { GetStaticProps, InferGetStaticPropsType } from "next";
// import Image from "next/image";
// import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

import ESSENCE from "essence";
import { type OneBotActions } from "onebot";

import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

export default function Home({ essence }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>ZJU IMPART</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Theme>
        <main className={styles.main}></main>
        <ThemePanel />
      </Theme>
    </>
  );
}

export const getStaticProps: GetStaticProps<{ essence: OneBotActions["get_essence_msg_list"][1] }> = (context) => {
  return { props: { essence: ESSENCE as any } };
};
