// tslint:disable
/**
 * Scraper API
 * This is a scraper API server.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { Configuration } from "./configuration.js";
import url from "node:url";

const BASE_PATH = "//localhost:8080/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
  csv: ",",
  ssv: " ",
  tsv: "\t",
  pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
  (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
  url: string;
  options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
  protected configuration: Configuration = {};

  constructor(
    configuration?: Configuration,
    protected basePath: string = BASE_PATH,
    protected fetch: FetchAPI = fetch
  ) {
    if (configuration) {
      this.configuration = configuration;
      this.basePath = configuration.basePath || this.basePath;
    }
  }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
  name = "RequiredError";
  constructor(
    public field: string,
    msg?: string
  ) {
    super(msg);
  }
}

/**
 *
 * @export
 * @interface TwitterDescription
 */
export interface TwitterDescription {
  /**
   *
   * @type {Array<TwitterURLElement>}
   * @memberof TwitterDescription
   */
  urls?: Array<TwitterURLElement>;
}
/**
 *
 * @export
 * @interface TwitterHashtag
 */
export interface TwitterHashtag {
  /**
   *
   * @type {string}
   * @memberof TwitterHashtag
   */
  text?: string;
}
/**
 *
 * @export
 * @interface TwitterMedia
 */
export interface TwitterMedia {
  /**
   *
   * @type {string}
   * @memberof TwitterMedia
   */
  displayUrl?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterMedia
   */
  expandedUrl?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterMedia
   */
  idStr?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterMedia
   */
  mediaUrlHttps?: string;
  /**
   *
   * @type {TwitterOriginalInfo}
   * @memberof TwitterMedia
   */
  originalInfo?: TwitterOriginalInfo;
  /**
   *
   * @type {TwitterSizes}
   * @memberof TwitterMedia
   */
  sizes?: TwitterSizes;
  /**
   *
   * @type {string}
   * @memberof TwitterMedia
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterMedia
   */
  url?: string;
  /**
   *
   * @type {TwitterMediaVideoInfo}
   * @memberof TwitterMedia
   */
  videoInfo?: TwitterMediaVideoInfo;
}
/**
 *
 * @export
 * @interface TwitterMediaVideoInfo
 */
export interface TwitterMediaVideoInfo {
  /**
   *
   * @type {Array<number>}
   * @memberof TwitterMediaVideoInfo
   */
  aspectRatio?: Array<number>;
  /**
   *
   * @type {number}
   * @memberof TwitterMediaVideoInfo
   */
  durationMillis?: number;
  /**
   *
   * @type {Array<TwitterMediaVideoInfoVariants>}
   * @memberof TwitterMediaVideoInfo
   */
  variants?: Array<TwitterMediaVideoInfoVariants>;
}
/**
 *
 * @export
 * @interface TwitterMediaVideoInfoVariants
 */
export interface TwitterMediaVideoInfoVariants {
  /**
   *
   * @type {string}
   * @memberof TwitterMediaVideoInfoVariants
   */
  contentType?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterMediaVideoInfoVariants
   */
  url?: string;
}
/**
 *
 * @export
 * @interface TwitterOriginalInfo
 */
export interface TwitterOriginalInfo {
  /**
   *
   * @type {number}
   * @memberof TwitterOriginalInfo
   */
  height?: number;
  /**
   *
   * @type {number}
   * @memberof TwitterOriginalInfo
   */
  width?: number;
}
/**
 *
 * @export
 * @interface TwitterPurpleEntities
 */
export interface TwitterPurpleEntities {
  /**
   *
   * @type {TwitterDescription}
   * @memberof TwitterPurpleEntities
   */
  description?: TwitterDescription;
  /**
   *
   * @type {TwitterDescription}
   * @memberof TwitterPurpleEntities
   */
  url?: TwitterDescription;
}
/**
 *
 * @export
 * @interface TwitterSizes
 */
export interface TwitterSizes {
  /**
   *
   * @type {TwitterThumbClass}
   * @memberof TwitterSizes
   */
  large?: TwitterThumbClass;
  /**
   *
   * @type {TwitterThumbClass}
   * @memberof TwitterSizes
   */
  medium?: TwitterThumbClass;
  /**
   *
   * @type {TwitterThumbClass}
   * @memberof TwitterSizes
   */
  small?: TwitterThumbClass;
  /**
   *
   * @type {TwitterThumbClass}
   * @memberof TwitterSizes
   */
  thumb?: TwitterThumbClass;
}
/**
 *
 * @export
 * @interface TwitterThumbClass
 */
export interface TwitterThumbClass {
  /**
   *
   * @type {number}
   * @memberof TwitterThumbClass
   */
  h?: number;
  /**
   *
   * @type {string}
   * @memberof TwitterThumbClass
   */
  resize?: string;
  /**
   *
   * @type {number}
   * @memberof TwitterThumbClass
   */
  w?: number;
}
/**
 *
 * @export
 * @interface TwitterTimelineTweetItem
 */
export interface TwitterTimelineTweetItem {
  /**
   *
   * @type {string}
   * @memberof TwitterTimelineTweetItem
   */
  itemType?: string;
  /**
   *
   * @type {TwitterTimelineTweetItemTweetResults}
   * @memberof TwitterTimelineTweetItem
   */
  tweetResults?: TwitterTimelineTweetItemTweetResults;
}
/**
 *
 * @export
 * @interface TwitterTimelineTweetItemTweetResults
 */
export interface TwitterTimelineTweetItemTweetResults {
  /**
   *
   * @type {TwitterTimelineTweetResult}
   * @memberof TwitterTimelineTweetItemTweetResults
   */
  result?: TwitterTimelineTweetResult;
}
/**
 *
 * @export
 * @interface TwitterTimelineTweetLegacy
 */
export interface TwitterTimelineTweetLegacy {
  /**
   *
   * @type {number}
   * @memberof TwitterTimelineTweetLegacy
   */
  bookmarkCount?: number;
  /**
   *
   * @type {string}
   * @memberof TwitterTimelineTweetLegacy
   */
  createdAt?: string;
  /**
   *
   * @type {TwitterTweetEntities}
   * @memberof TwitterTimelineTweetLegacy
   */
  entities?: TwitterTweetEntities;
  /**
   *
   * @type {number}
   * @memberof TwitterTimelineTweetLegacy
   */
  favoriteCount?: number;
  /**
   *
   * @type {string}
   * @memberof TwitterTimelineTweetLegacy
   */
  fullText?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterTimelineTweetLegacy
   */
  idStr?: string;
  /**
   *
   * @type {boolean}
   * @memberof TwitterTimelineTweetLegacy
   */
  isQuoteStatus?: boolean;
  /**
   *
   * @type {number}
   * @memberof TwitterTimelineTweetLegacy
   */
  quoteCount?: number;
  /**
   *
   * @type {number}
   * @memberof TwitterTimelineTweetLegacy
   */
  replyCount?: number;
  /**
   *
   * @type {number}
   * @memberof TwitterTimelineTweetLegacy
   */
  retweetCount?: number;
  /**
   *
   * @type {TwitterTimelineTweetItemTweetResults}
   * @memberof TwitterTimelineTweetLegacy
   */
  retweetedStatusResult?: TwitterTimelineTweetItemTweetResults;
  /**
   *
   * @type {string}
   * @memberof TwitterTimelineTweetLegacy
   */
  userIdStr?: string;
}
/**
 *
 * @export
 * @interface TwitterTimelineTweetResult
 */
export interface TwitterTimelineTweetResult {
  /**
   *
   * @type {TwitterTimelineTweetResultCore}
   * @memberof TwitterTimelineTweetResult
   */
  core?: TwitterTimelineTweetResultCore;
  /**
   *
   * @type {TwitterTimelineTweetLegacy}
   * @memberof TwitterTimelineTweetResult
   */
  legacy?: TwitterTimelineTweetLegacy;
  /**
   *
   * @type {string}
   * @memberof TwitterTimelineTweetResult
   */
  restId?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterTimelineTweetResult
   */
  source?: string;
  /**
   *
   * @type {TwitterViews}
   * @memberof TwitterTimelineTweetResult
   */
  views?: TwitterViews;
}
/**
 *
 * @export
 * @interface TwitterTimelineTweetResultCore
 */
export interface TwitterTimelineTweetResultCore {
  /**
   *
   * @type {TwitterUserResult}
   * @memberof TwitterTimelineTweetResultCore
   */
  userResults?: TwitterUserResult;
}
/**
 *
 * @export
 * @interface TwitterTweetEntities
 */
export interface TwitterTweetEntities {
  /**
   *
   * @type {Array<TwitterHashtag>}
   * @memberof TwitterTweetEntities
   */
  hashtags?: Array<TwitterHashtag>;
  /**
   *
   * @type {Array<TwitterMedia>}
   * @memberof TwitterTweetEntities
   */
  media?: Array<TwitterMedia>;
  /**
   *
   * @type {Array<any>}
   * @memberof TwitterTweetEntities
   */
  symbols?: Array<any>;
  /**
   *
   * @type {Array<TwitterURLElement>}
   * @memberof TwitterTweetEntities
   */
  urls?: Array<TwitterURLElement>;
  /**
   *
   * @type {Array<TwitterUserMention>}
   * @memberof TwitterTweetEntities
   */
  userMentions?: Array<TwitterUserMention>;
}
/**
 *
 * @export
 * @interface TwitterTweetEntry
 */
export interface TwitterTweetEntry {
  /**
   *
   * @type {TwitterTweetEntryContent}
   * @memberof TwitterTweetEntry
   */
  content?: TwitterTweetEntryContent;
  /**
   *
   * @type {string}
   * @memberof TwitterTweetEntry
   */
  entryId?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterTweetEntry
   */
  sortIndex?: string;
}
/**
 *
 * @export
 * @interface TwitterTweetEntryContent
 */
export interface TwitterTweetEntryContent {
  /**
   *
   * @type {string}
   * @memberof TwitterTweetEntryContent
   */
  entryType?: string;
  /**
   *
   * @type {TwitterTimelineTweetItem}
   * @memberof TwitterTweetEntryContent
   */
  itemContent?: TwitterTimelineTweetItem;
  /**
   *
   * @type {Array<TwitterTweetEntryContentItems>}
   * @memberof TwitterTweetEntryContent
   */
  items?: Array<TwitterTweetEntryContentItems>;
}
/**
 *
 * @export
 * @interface TwitterTweetEntryContentItem
 */
export interface TwitterTweetEntryContentItem {
  /**
   *
   * @type {TwitterTimelineTweetItem}
   * @memberof TwitterTweetEntryContentItem
   */
  itemContent?: TwitterTimelineTweetItem;
}
/**
 *
 * @export
 * @interface TwitterTweetEntryContentItems
 */
export interface TwitterTweetEntryContentItems {
  /**
   *
   * @type {string}
   * @memberof TwitterTweetEntryContentItems
   */
  entryId?: string;
  /**
   *
   * @type {TwitterTweetEntryContentItem}
   * @memberof TwitterTweetEntryContentItems
   */
  item?: TwitterTweetEntryContentItem;
}
/**
 *
 * @export
 * @interface TwitterURLElement
 */
export interface TwitterURLElement {
  /**
   *
   * @type {string}
   * @memberof TwitterURLElement
   */
  displayUrl?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterURLElement
   */
  expandedUrl?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterURLElement
   */
  url?: string;
}
/**
 *
 * @export
 * @interface TwitterUserLegacy
 */
export interface TwitterUserLegacy {
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  canDm?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  canMediaTag?: boolean;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  createdAt?: string;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  defaultProfile?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  defaultProfileImage?: boolean;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  description?: string;
  /**
   *
   * @type {TwitterPurpleEntities}
   * @memberof TwitterUserLegacy
   */
  entities?: TwitterPurpleEntities;
  /**
   *
   * @type {number}
   * @memberof TwitterUserLegacy
   */
  fastFollowersCount?: number;
  /**
   *
   * @type {number}
   * @memberof TwitterUserLegacy
   */
  favouritesCount?: number;
  /**
   *
   * @type {number}
   * @memberof TwitterUserLegacy
   */
  followersCount?: number;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  following?: boolean;
  /**
   *
   * @type {number}
   * @memberof TwitterUserLegacy
   */
  friendsCount?: number;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  hasCustomTimelines?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  isTranslator?: boolean;
  /**
   *
   * @type {number}
   * @memberof TwitterUserLegacy
   */
  listedCount?: number;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  location?: string;
  /**
   *
   * @type {number}
   * @memberof TwitterUserLegacy
   */
  mediaCount?: number;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof TwitterUserLegacy
   */
  normalFollowersCount?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof TwitterUserLegacy
   */
  pinnedTweetIdsStr?: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  possiblySensitive?: boolean;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  profileBannerUrl?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  profileImageUrlHttps?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  profileInterstitialType?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  screenName?: string;
  /**
   *
   * @type {number}
   * @memberof TwitterUserLegacy
   */
  statusesCount?: number;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  translatorType?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  url?: string;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  verified?: boolean;
  /**
   *
   * @type {string}
   * @memberof TwitterUserLegacy
   */
  verifiedType?: string;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserLegacy
   */
  wantRetweets?: boolean;
  /**
   *
   * @type {Array<any>}
   * @memberof TwitterUserLegacy
   */
  withheldInCountries?: Array<any>;
}
/**
 *
 * @export
 * @interface TwitterUserMention
 */
export interface TwitterUserMention {
  /**
   *
   * @type {string}
   * @memberof TwitterUserMention
   */
  idStr?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof TwitterUserMention
   */
  indices?: Array<number>;
  /**
   *
   * @type {string}
   * @memberof TwitterUserMention
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterUserMention
   */
  screenName?: string;
}
/**
 *
 * @export
 * @interface TwitterUserResult
 */
export interface TwitterUserResult {
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserResult
   */
  hasGraduatedAccess?: boolean;
  /**
   *
   * @type {string}
   * @memberof TwitterUserResult
   */
  id?: string;
  /**
   *
   * @type {boolean}
   * @memberof TwitterUserResult
   */
  isBlueVerified?: boolean;
  /**
   *
   * @type {TwitterUserLegacy}
   * @memberof TwitterUserResult
   */
  legacy?: TwitterUserLegacy;
  /**
   *
   * @type {string}
   * @memberof TwitterUserResult
   */
  parodyCommentaryFanLabel?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterUserResult
   */
  profileImageShape?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterUserResult
   */
  restId?: string;
}
/**
 *
 * @export
 * @interface TwitterViews
 */
export interface TwitterViews {
  /**
   *
   * @type {string}
   * @memberof TwitterViews
   */
  count?: string;
  /**
   *
   * @type {string}
   * @memberof TwitterViews
   */
  state?: string;
}
/**
 *
 * @export
 * @interface YoutubeYouTubeVideo
 */
export interface YoutubeYouTubeVideo {
  /**
   *
   * @type {string}
   * @memberof YoutubeYouTubeVideo
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof YoutubeYouTubeVideo
   */
  publishedAt?: string;
  /**
   *
   * @type {string}
   * @memberof YoutubeYouTubeVideo
   */
  thumbnailUrl?: string;
  /**
   *
   * @type {string}
   * @memberof YoutubeYouTubeVideo
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof YoutubeYouTubeVideo
   */
  videoId?: string;
}
/**
 * TwitterApi - fetch parameter creator
 * @export
 */
export const TwitterApiFetchParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Get a list of tweets for a given user
     * @summary Get user tweets
     * @param {string} userName Twitter username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    twitterUserNamePostsGet(userName: string, options: any = {}): FetchArgs {
      // verify required parameter 'userName' is not null or undefined
      if (userName === null || userName === undefined) {
        throw new RequiredError(
          "userName",
          "Required parameter userName was null or undefined when calling twitterUserNamePostsGet."
        );
      }
      const localVarPath = `/twitter/{userName}/posts`.replace(`{${"userName"}}`, encodeURIComponent(String(userName)));
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TwitterApi - functional programming interface
 * @export
 */
export const TwitterApiFp = function (configuration?: Configuration) {
  return {
    /**
     * Get a list of tweets for a given user
     * @summary Get user tweets
     * @param {string} userName Twitter username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    twitterUserNamePostsGet(
      userName: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<Array<TwitterTweetEntry>> {
      const localVarFetchArgs = TwitterApiFetchParamCreator(configuration).twitterUserNamePostsGet(userName, options);
      return async (fetch: FetchAPI = globalThis.fetch, basePath: string = BASE_PATH) => {
        const response = await fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options);
        if (response.status >= 200 && response.status < 300) {
          return response.json();
        } else {
          throw response;
        }
      };
    },
  };
};

/**
 * TwitterApi - factory interface
 * @export
 */
export const TwitterApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
  return {
    /**
     * Get a list of tweets for a given user
     * @summary Get user tweets
     * @param {string} userName Twitter username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    twitterUserNamePostsGet(userName: string, options?: any) {
      return TwitterApiFp(configuration).twitterUserNamePostsGet(userName, options)(fetch, basePath);
    },
  };
};

/**
 * TwitterApi - object-oriented interface
 * @export
 * @class TwitterApi
 * @extends {BaseAPI}
 */
export class TwitterApi extends BaseAPI {
  /**
   * Get a list of tweets for a given user
   * @summary Get user tweets
   * @param {string} userName Twitter username
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TwitterApi
   */
  public twitterUserNamePostsGet(userName: string, options?: any) {
    return TwitterApiFp(this.configuration).twitterUserNamePostsGet(userName, options)(this.fetch, this.basePath);
  }
}
/**
 * YoutubeApi - fetch parameter creator
 * @export
 */
export const YoutubeApiFetchParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Get a list of videos for a given YouTube channel
     * @summary Get channel videos
     * @param {string} channelName YouTube channel name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    youtubeChannelNameVideosGet(channelName: string, options: any = {}): FetchArgs {
      // verify required parameter 'channelName' is not null or undefined
      if (channelName === null || channelName === undefined) {
        throw new RequiredError(
          "channelName",
          "Required parameter channelName was null or undefined when calling youtubeChannelNameVideosGet."
        );
      }
      const localVarPath = `/youtube/{channelName}/videos`.replace(
        `{${"channelName"}}`,
        encodeURIComponent(String(channelName))
      );
      const localVarUrlObj = url.parse(localVarPath, true);
      const localVarRequestOptions = Object.assign({ method: "GET" }, options);
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      localVarUrlObj.search = null;
      localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

      return {
        url: url.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * YoutubeApi - functional programming interface
 * @export
 */
export const YoutubeApiFp = function (configuration?: Configuration) {
  return {
    /**
     * Get a list of videos for a given YouTube channel
     * @summary Get channel videos
     * @param {string} channelName YouTube channel name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    youtubeChannelNameVideosGet(
      channelName: string,
      options?: any
    ): (fetch?: FetchAPI, basePath?: string) => Promise<Array<YoutubeYouTubeVideo>> {
      const localVarFetchArgs = YoutubeApiFetchParamCreator(configuration).youtubeChannelNameVideosGet(
        channelName,
        options
      );
      return async (fetch: FetchAPI = globalThis.fetch, basePath: string = BASE_PATH) => {
        const response = await fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options);
        if (response.status >= 200 && response.status < 300) {
          return response.json();
        } else {
          throw response;
        }
      };
    },
  };
};

/**
 * YoutubeApi - factory interface
 * @export
 */
export const YoutubeApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
  return {
    /**
     * Get a list of videos for a given YouTube channel
     * @summary Get channel videos
     * @param {string} channelName YouTube channel name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    youtubeChannelNameVideosGet(channelName: string, options?: any) {
      return YoutubeApiFp(configuration).youtubeChannelNameVideosGet(channelName, options)(fetch, basePath);
    },
  };
};

/**
 * YoutubeApi - object-oriented interface
 * @export
 * @class YoutubeApi
 * @extends {BaseAPI}
 */
export class YoutubeApi extends BaseAPI {
  /**
   * Get a list of videos for a given YouTube channel
   * @summary Get channel videos
   * @param {string} channelName YouTube channel name
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof YoutubeApi
   */
  public youtubeChannelNameVideosGet(channelName: string, options?: any) {
    return YoutubeApiFp(this.configuration).youtubeChannelNameVideosGet(channelName, options)(
      this.fetch,
      this.basePath
    );
  }
}
