// tslint:disable
/**
 * Scraper API
 * This is a scraper API server.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api.js";
export * from "./configuration.js";
