// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type { Client, Options as Options2, TDataShape } from "./client/index.js";
import type {
  GetTwitterByUserNamePostsData,
  GetTwitterByUserNamePostsErrors,
  GetTwitterByUserNamePostsResponses,
  GetYoutubeByChannelNameVideosData,
  GetYoutubeByChannelNameVideosErrors,
  GetYoutubeByChannelNameVideosResponses,
} from "./types.gen.js";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get user tweets
 *
 * Get a list of tweets for a given user
 */
export const getTwitterByUserNamePosts = <ThrowOnError extends boolean = false>(
  options: Options<GetTwitterByUserNamePostsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetTwitterByUserNamePostsResponses, GetTwitterByUserNamePostsErrors, ThrowOnError>({
    url: "/twitter/{userName}/posts",
    ...options,
  });

/**
 * Get channel videos
 *
 * Get a list of videos for a given YouTube channel
 */
export const getYoutubeByChannelNameVideos = <ThrowOnError extends boolean = false>(
  options: Options<GetYoutubeByChannelNameVideosData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetYoutubeByChannelNameVideosResponses,
    GetYoutubeByChannelNameVideosErrors,
    ThrowOnError
  >({ url: "/youtube/{channelName}/videos", ...options });
