// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://localhost:8080/" | (string & {});
};

export type TwitterDescription = {
  urls?: Array<TwitterUrlElement>;
};

export type TwitterHashtag = {
  text?: string;
};

export type TwitterMedia = {
  display_url?: string;
  expanded_url?: string;
  id_str?: string;
  media_url_https?: string;
  original_info?: TwitterOriginalInfo;
  sizes?: TwitterSizes;
  type?: string;
  url?: string;
  video_info?: {
    aspect_ratio?: Array<number>;
    duration_millis?: number;
    variants?: Array<{
      bitrate?: number;
      content_type?: string;
      url?: string;
    }>;
  };
};

export type TwitterOriginalInfo = {
  height?: number;
  width?: number;
};

export type TwitterPurpleEntities = {
  description?: TwitterDescription;
  url?: TwitterDescription;
};

export type TwitterSizes = {
  large?: TwitterThumbClass;
  medium?: TwitterThumbClass;
  small?: TwitterThumbClass;
  thumb?: TwitterThumbClass;
};

export type TwitterThumbClass = {
  h?: number;
  resize?: string;
  w?: number;
};

export type TwitterTimelineTweetItem = {
  itemType?: string;
  tweet_results?: {
    result?: TwitterTimelineTweetResult;
  };
};

export type TwitterTimelineTweetLegacy = {
  bookmark_count?: number;
  created_at?: string;
  entities?: TwitterTweetEntities;
  favorite_count?: number;
  full_text?: string;
  id_str?: string;
  is_quote_status?: boolean;
  quote_count?: number;
  reply_count?: number;
  retweet_count?: number;
  retweeted_status_result?: {
    result?: TwitterTimelineTweetResult;
  };
  user_id_str?: string;
};

export type TwitterTimelineTweetResult = {
  core?: {
    user_results?: TwitterUserResult;
  };
  legacy?: TwitterTimelineTweetLegacy;
  rest_id?: string;
  source?: string;
  views?: TwitterViews;
};

export type TwitterTweetEntities = {
  hashtags?: Array<TwitterHashtag>;
  media?: Array<TwitterMedia>;
  symbols?: Array<unknown>;
  urls?: Array<TwitterUrlElement>;
  user_mentions?: Array<TwitterUserMention>;
};

export type TwitterTweetEntry = {
  content?: {
    entryType?: string;
    itemContent?: TwitterTimelineTweetItem;
    items?: Array<{
      entryId?: string;
      item?: {
        itemContent?: TwitterTimelineTweetItem;
      };
    }>;
  };
  entryId?: string;
  sortIndex?: string;
};

export type TwitterUrlElement = {
  display_url?: string;
  expanded_url?: string;
  url?: string;
};

export type TwitterUserLegacy = {
  can_dm?: boolean;
  can_media_tag?: boolean;
  created_at?: string;
  default_profile?: boolean;
  default_profile_image?: boolean;
  description?: string;
  entities?: TwitterPurpleEntities;
  fast_followers_count?: number;
  favourites_count?: number;
  followers_count?: number;
  following?: boolean;
  friends_count?: number;
  has_custom_timelines?: boolean;
  is_translator?: boolean;
  listed_count?: number;
  location?: string;
  media_count?: number;
  name?: string;
  normal_followers_count?: number;
  pinned_tweet_ids_str?: Array<string>;
  possibly_sensitive?: boolean;
  profile_banner_url?: string;
  profile_image_url_https?: string;
  profile_interstitial_type?: string;
  screen_name?: string;
  statuses_count?: number;
  translator_type?: string;
  url?: string;
  verified?: boolean;
  verified_type?: string;
  want_retweets?: boolean;
  withheld_in_countries?: Array<unknown>;
};

export type TwitterUserMention = {
  id_str?: string;
  indices?: Array<number>;
  name?: string;
  screen_name?: string;
};

export type TwitterUserResult = {
  has_graduated_access?: boolean;
  id?: string;
  is_blue_verified?: boolean;
  legacy?: TwitterUserLegacy;
  parody_commentary_fan_label?: string;
  profile_image_shape?: string;
  rest_id?: string;
};

export type TwitterViews = {
  count?: string;
  state?: string;
};

export type YoutubeYouTubeVideo = {
  description?: string;
  publishedAt?: string;
  thumbnailUrl?: string;
  title?: string;
  videoId?: string;
};

export type GetTwitterByUserNamePostsData = {
  body?: never;
  path: {
    /**
     * Twitter username
     */
    userName: string;
  };
  query?: never;
  url: "/twitter/{userName}/posts";
};

export type GetTwitterByUserNamePostsErrors = {
  /**
   * Internal Server Error
   */
  500: string;
};

export type GetTwitterByUserNamePostsError = GetTwitterByUserNamePostsErrors[keyof GetTwitterByUserNamePostsErrors];

export type GetTwitterByUserNamePostsResponses = {
  /**
   * OK
   */
  200: Array<TwitterTweetEntry>;
};

export type GetTwitterByUserNamePostsResponse =
  GetTwitterByUserNamePostsResponses[keyof GetTwitterByUserNamePostsResponses];

export type GetYoutubeByChannelNameVideosData = {
  body?: never;
  path: {
    /**
     * YouTube channel name
     */
    channelName: string;
  };
  query?: never;
  url: "/youtube/{channelName}/videos";
};

export type GetYoutubeByChannelNameVideosErrors = {
  /**
   * Bad Request
   */
  400: string;
  /**
   * Internal Server Error
   */
  500: string;
};

export type GetYoutubeByChannelNameVideosError =
  GetYoutubeByChannelNameVideosErrors[keyof GetYoutubeByChannelNameVideosErrors];

export type GetYoutubeByChannelNameVideosResponses = {
  /**
   * OK
   */
  200: Array<YoutubeYouTubeVideo>;
};

export type GetYoutubeByChannelNameVideosResponse =
  GetYoutubeByChannelNameVideosResponses[keyof GetYoutubeByChannelNameVideosResponses];
