// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://raw.githubusercontent.com" | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ImageHashResponse
 */
export type ImageHashResponse = {
  /**
   * Perceptual Hash
   */
  perceptual_hash: string;
  pdqhash: PdqHashResult;
};

/**
 * ImageUrlRequest
 */
export type ImageUrlRequest = {
  /**
   * Url
   */
  url: string;
};

/**
 * PdqHashResult
 */
export type PdqHashResult = {
  /**
   * Original
   */
  original: string;
  /**
   * Rotated 90
   */
  rotated_90: string;
  /**
   * Rotated 180
   */
  rotated_180: string;
  /**
   * Rotated 270
   */
  rotated_270: string;
  /**
   * Flipped Vertical
   */
  flipped_vertical: string;
  /**
   * Flipped Horizontal
   */
  flipped_horizontal: string;
  /**
   * Rotated 90 Flipped
   */
  rotated_90_flipped: string;
  /**
   * Rotated 270 Flipped
   */
  rotated_270_flipped: string;
  /**
   * Quality
   */
  quality: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type ProcessImageGetImageHashPostData = {
  body: ImageUrlRequest;
  path?: never;
  query?: never;
  url: "/get-image-hash";
};

export type ProcessImageGetImageHashPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProcessImageGetImageHashPostError =
  ProcessImageGetImageHashPostErrors[keyof ProcessImageGetImageHashPostErrors];

export type ProcessImageGetImageHashPostResponses = {
  /**
   * Successful Response
   */
  200: ImageHashResponse;
};

export type ProcessImageGetImageHashPostResponse =
  ProcessImageGetImageHashPostResponses[keyof ProcessImageGetImageHashPostResponses];
