// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ImageHashResponse
 */
export type ImageHashResponse = {
  /**
   * Perceptual Hash
   */
  perceptual_hash: string;
  /**
   * Pdqhash
   */
  pdqhash: {
    [key: string]: unknown;
  };
};

/**
 * ImageUrlRequest
 */
export type ImageUrlRequest = {
  /**
   * Url
   */
  url: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type ProcessImageGetImageHashPostData = {
  body: ImageUrlRequest;
  path?: never;
  query?: never;
  url: "/get-image-hash";
};

export type ProcessImageGetImageHashPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ProcessImageGetImageHashPostError =
  ProcessImageGetImageHashPostErrors[keyof ProcessImageGetImageHashPostErrors];

export type ProcessImageGetImageHashPostResponses = {
  /**
   * Successful Response
   */
  200: ImageHashResponse;
};

export type ProcessImageGetImageHashPostResponse =
  ProcessImageGetImageHashPostResponses[keyof ProcessImageGetImageHashPostResponses];
